layers:
  - ConvolutionLayer:
      - weights
      - biases
      - dim:
        - neurons
        - channels
        - height
        - width
      - name
      - padding
      - stride
      - bottom
      - top

  - LinearLayer:
     - weights
      - biases
      - dim:
        - neurons
        - channels
        - height
        - width
      - name
      - bottom
      - top